In [1]:
import pandas as pd
from pathlib import Path

file_path = Path("../data/raw/census/dp05.csv")

df_dp05 = pd.read_csv(file_path, dtype=str)

print("Dataset shape:", df_dp05.shape)
print("\nFirst 10 rows:")
display(df_dp05.head(10))

print("\nColumn names:")
print(df_dp05.columns.tolist())

Dataset shape: (113, 57)

First 10 rows:

,Label (Grouping),"Barnstable County, Massachusetts!!Estimate","Barnstable County, Massachusetts!!Margin of Error","Barnstable County, Massachusetts!!Percent","Barnstable County, Massachusetts!!Percent Margin of Error","Berkshire County, Massachusetts!!Estimate","Berkshire County, Massachusetts!!Margin of Error","Berkshire County, Massachusetts!!Percent","Berkshire County, Massachusetts!!Percent Margin of Error","Bristol County, Massachusetts!!Estimate",...,"Plymouth County, Massachusetts!!Percent","Plymouth County, Massachusetts!!Percent Margin of Error","Suffolk County, Massachusetts!!Estimate","Suffolk County, Massachusetts!!Margin of Error","Suffolk County, Massachusetts!!Percent","Suffolk County, Massachusetts!!Percent Margin of Error","Worcester County, Massachusetts!!Estimate","Worcester County, Massachusetts!!Margin of Error","Worcester County, Massachusetts!!Percent","Worcester County, Massachusetts!!Percent Margin of Error"
0,SEX AND AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total population,"231,668",*****,"231,668",(X),"129,430",*****,"129,430",(X),"582,270",...,"535,075",(X),"785,121",*****,"785,121",(X),"867,788",*****,"867,788",(X)
2,Male,"111,539",±274,48.1%,±0.1,"63,381",±182,49.0%,±0.1,"284,657",...,48.9%,±0.1,"378,760",±175,48.2%,±0.1,"431,017",±87,49.7%,±0.1
3,Female,"120,129",±274,51.9%,±0.1,"66,049",±182,51.0%,±0.1,"297,613",...,51.1%,±0.1,"406,361",±175,51.8%,±0.1,"436,771",±87,50.3%,±0.1
4,Sex ratio (males per 100 females),92.8,±0.4,(X),(X),96.0,±0.5,(X),(X),95.6,...,(X),(X),93.2,±0.1,(X),(X),98.7,±0.1,(X),(X)
5,Under 5 years,"7,855",±28,3.4%,±0.1,"4,925",±7,3.8%,±0.1,"29,356",...,5.1%,±0.1,"37,885",±129,4.8%,±0.1,"44,639",±49,5.1%,±0.1
6,5 to 9 years,"9,004",±718,3.9%,±0.3,"5,818",±369,4.5%,±0.3,"31,983",...,5.5%,±0.2,"31,533","±1,308",4.0%,±0.2,"47,802","±1,561",5.5%,±0.2
7,10 to 14 years,"9,227",±731,4.0%,±0.3,"5,681",±372,4.4%,±0.3,"35,789",...,6.1%,±0.2,"35,292","±1,298",4.5%,±0.2,"53,075","±1,561",6.1%,±0.2
8,15 to 19 years,"10,647",±282,4.6%,±0.1,"8,507",±291,6.6%,±0.2,"36,598",...,6.2%,±0.1,"56,176",±606,7.2%,±0.1,"57,564",±58,6.6%,±0.1
9,20 to 24 years,"11,203",±313,4.8%,±0.1,"8,412",±274,6.5%,±0.2,"36,021",...,5.9%,±0.1,"72,134",±643,9.2%,±0.1,"55,659",±57,6.4%,±0.1

Column names:
['Label (Grouping)', 'Barnstable County, Massachusetts!!Estimate', 'Barnstable County, Massachusetts!!Margin of Error', 'Barnstable County, Massachusetts!!Percent', 'Barnstable County, Massachusetts!!Percent Margin of Error', 'Berkshire County, Massachusetts!!Estimate', 'Berkshire County, Massachusetts!!Margin of Error', 'Berkshire County, Massachusetts!!Percent', 'Berkshire County, Massachusetts!!Percent Margin of Error', 'Bristol County, Massachusetts!!Estimate', 'Bristol County, Massachusetts!!Margin of Error', 'Bristol County, Massachusetts!!Percent', 'Bristol County, Massachusetts!!Percent Margin of Error', 'Dukes County, Massachusetts!!Estimate', 'Dukes County, Massachusetts!!Margin of Error', 'Dukes County, Massachusetts!!Percent', 'Dukes County, Massachusetts!!Percent Margin of Error', 'Essex County, Massachusetts!!Estimate', 'Essex County, Massachusetts!!Margin of Error', 'Essex County, Massachusetts!!Percent', 'Essex County, Massachusetts!!Percent Margin of Error', 'Franklin County, Massachusetts!!Estimate', 'Franklin County, Massachusetts!!Margin of Error', 'Franklin County, Massachusetts!!Percent', 'Franklin County, Massachusetts!!Percent Margin of Error', 'Hampden County, Massachusetts!!Estimate', 'Hampden County, Massachusetts!!Margin of Error', 'Hampden County, Massachusetts!!Percent', 'Hampden County, Massachusetts!!Percent Margin of Error', 'Hampshire County, Massachusetts!!Estimate', 'Hampshire County, Massachusetts!!Margin of Error', 'Hampshire County, Massachusetts!!Percent', 'Hampshire County, Massachusetts!!Percent Margin of Error', 'Middlesex County, Massachusetts!!Estimate', 'Middlesex County, Massachusetts!!Margin of Error', 'Middlesex County, Massachusetts!!Percent', 'Middlesex County, Massachusetts!!Percent Margin of Error', 'Nantucket County, Massachusetts!!Estimate', 'Nantucket County, Massachusetts!!Margin of Error', 'Nantucket County, Massachusetts!!Percent', 'Nantucket County, Massachusetts!!Percent Margin of Error', 'Norfolk County, Massachusetts!!Estimate', 'Norfolk County, Massachusetts!!Margin of Error', 'Norfolk County, Massachusetts!!Percent', 'Norfolk County, Massachusetts!!Percent Margin of Error', 'Plymouth County, Massachusetts!!Estimate', 'Plymouth County, Massachusetts!!Margin of Error', 'Plymouth County, Massachusetts!!Percent', 'Plymouth County, Massachusetts!!Percent Margin of Error', 'Suffolk County, Massachusetts!!Estimate', 'Suffolk County, Massachusetts!!Margin of Error', 'Suffolk County, Massachusetts!!Percent', 'Suffolk County, Massachusetts!!Percent Margin of Error', 'Worcester County, Massachusetts!!Estimate', 'Worcester County, Massachusetts!!Margin of Error', 'Worcester County, Massachusetts!!Percent', 'Worcester County, Massachusetts!!Percent Margin of Error']

In [2]:
print("Dataset shape:", df_dp05.shape)

print("\nData types:")
print(df_dp05.dtypes.value_counts())

print("\nExact duplicate rows:", df_dp05.duplicated().sum())

print("\nUnique labels:", df_dp05["Label (Grouping)"].nunique())

print("\nMissing values per column:")
print(df_dp05.isna().sum())

print("\nFirst 30 demographic labels:")
for i, label in enumerate(df_dp05["Label (Grouping)"].head(30)):
    print(i, ":", repr(label))

Dataset shape: (113, 57)

Data types:
str    57
Name: count, dtype: int64

Exact duplicate rows: 5

Unique labels: 101

Missing values per column:
Label (Grouping)                                             0
Barnstable County, Massachusetts!!Estimate                   5
Barnstable County, Massachusetts!!Margin of Error            5
Barnstable County, Massachusetts!!Percent                    5
Barnstable County, Massachusetts!!Percent Margin of Error    5
Berkshire County, Massachusetts!!Estimate                    5
Berkshire County, Massachusetts!!Margin of Error             5
Berkshire County, Massachusetts!!Percent                     5
Berkshire County, Massachusetts!!Percent Margin of Error     5
Bristol County, Massachusetts!!Estimate                      5
Bristol County, Massachusetts!!Margin of Error               5
Bristol County, Massachusetts!!Percent                       5
Bristol County, Massachusetts!!Percent Margin of Error       5
Dukes County, Massachusetts!!Estimate                        5
Dukes County, Massachusetts!!Margin of Error                 5
Dukes County, Massachusetts!!Percent                         5
Dukes County, Massachusetts!!Percent Margin of Error         5
Essex County, Massachusetts!!Estimate                        5
Essex County, Massachusetts!!Margin of Error                 5
Essex County, Massachusetts!!Percent                         5
Essex County, Massachusetts!!Percent Margin of Error         5
Franklin County, Massachusetts!!Estimate                     5
Franklin County, Massachusetts!!Margin of Error              5
Franklin County, Massachusetts!!Percent                      5
Franklin County, Massachusetts!!Percent Margin of Error      5
Hampden County, Massachusetts!!Estimate                      5
Hampden County, Massachusetts!!Margin of Error               5
Hampden County, Massachusetts!!Percent                       5
Hampden County, Massachusetts!!Percent Margin of Error       5
Hampshire County, Massachusetts!!Estimate                    5
Hampshire County, Massachusetts!!Margin of Error             5
Hampshire County, Massachusetts!!Percent                     5
Hampshire County, Massachusetts!!Percent Margin of Error     5
Middlesex County, Massachusetts!!Estimate                    5
Middlesex County, Massachusetts!!Margin of Error             5
Middlesex County, Massachusetts!!Percent                     5
Middlesex County, Massachusetts!!Percent Margin of Error     5
Nantucket County, Massachusetts!!Estimate                    5
Nantucket County, Massachusetts!!Margin of Error             5
Nantucket County, Massachusetts!!Percent                     5
Nantucket County, Massachusetts!!Percent Margin of Error     5
Norfolk County, Massachusetts!!Estimate                      5
Norfolk County, Massachusetts!!Margin of Error               5
Norfolk County, Massachusetts!!Percent                       5
Norfolk County, Massachusetts!!Percent Margin of Error       5
Plymouth County, Massachusetts!!Estimate                     5
Plymouth County, Massachusetts!!Margin of Error              5
Plymouth County, Massachusetts!!Percent                      5
Plymouth County, Massachusetts!!Percent Margin of Error      5
Suffolk County, Massachusetts!!Estimate                      5
Suffolk County, Massachusetts!!Margin of Error               5
Suffolk County, Massachusetts!!Percent                       5
Suffolk County, Massachusetts!!Percent Margin of Error       5
Worcester County, Massachusetts!!Estimate                    5
Worcester County, Massachusetts!!Margin of Error             5
Worcester County, Massachusetts!!Percent                     5
Worcester County, Massachusetts!!Percent Margin of Error     5
dtype: int64

First 30 demographic labels:
0 : 'SEX AND AGE'
1 : '\xa0\xa0\xa0\xa0Total population'
2 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Male'
3 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Female'
4 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Sex ratio (males per 100 females)'
5 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Under 5 years'
6 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa05 to 9 years'
7 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa010 to 14 years'
8 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa015 to 19 years'
9 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa020 to 24 years'
10 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa025 to 34 years'
11 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa035 to 44 years'
12 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa045 to 54 years'
13 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa055 to 59 years'
14 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa060 to 64 years'
15 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa065 to 74 years'
16 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa075 to 84 years'
17 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa085 years and over'
18 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Median age (years)'
19 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Under 18 years'
20 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa016 years and over'
21 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa018 years and over'
22 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa021 years and over'
23 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa062 years and over'
24 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa065 years and over'
25 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa018 years and over'
26 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Male'
27 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Female'
28 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0Sex ratio (males per 100 females)'
29 : '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa065 years and over'

In [3]:
labels_dp05 = df_dp05["Label (Grouping)"].str.strip()

for i, label in enumerate(labels_dp05):
    print(i, ":", repr(label))

0 : 'SEX AND AGE'
1 : 'Total population'
2 : 'Male'
3 : 'Female'
4 : 'Sex ratio (males per 100 females)'
5 : 'Under 5 years'
6 : '5 to 9 years'
7 : '10 to 14 years'
8 : '15 to 19 years'
9 : '20 to 24 years'
10 : '25 to 34 years'
11 : '35 to 44 years'
12 : '45 to 54 years'
13 : '55 to 59 years'
14 : '60 to 64 years'
15 : '65 to 74 years'
16 : '75 to 84 years'
17 : '85 years and over'
18 : 'Median age (years)'
19 : 'Under 18 years'
20 : '16 years and over'
21 : '18 years and over'
22 : '21 years and over'
23 : '62 years and over'
24 : '65 years and over'
25 : '18 years and over'
26 : 'Male'
27 : 'Female'
28 : 'Sex ratio (males per 100 females)'
29 : '65 years and over'
30 : 'Male'
31 : 'Female'
32 : 'Sex ratio (males per 100 females)'
33 : 'RACE'
34 : 'Total population'
35 : 'One race'
36 : 'Two or More Races'
37 : 'One race'
38 : 'White'
39 : 'Egyptian'
40 : 'English'
41 : 'German'
42 : 'Irish'
43 : 'Italian'
44 : 'Lebanese'
45 : 'Other White'
46 : 'Black or African American'
47 : 'African American'
48 : 'Ethiopian'
49 : 'Haitian'
50 : 'Jamaican'
51 : 'Nigerian'
52 : 'Somali'
53 : 'Other Black or African American'
54 : 'American Indian and Alaska Native'
55 : 'Aztec'
56 : 'Blackfeet Tribe of the Blackfeet Indian Reservation of Montana'
57 : 'Maya'
58 : 'Native Village of Barrow Inupiat Traditional Government'
59 : 'Navajo Nation'
60 : 'Nome Eskimo Community'
61 : 'Other American Indian and Alaska Native'
62 : 'Asian'
63 : 'Asian Indian'
64 : 'Chinese'
65 : 'Filipino'
66 : 'Japanese'
67 : 'Korean'
68 : 'Vietnamese'
69 : 'Other Asian'
70 : 'Native Hawaiian and Other Pacific Islander'
71 : 'Chamorro'
72 : 'Native Hawaiian'
73 : 'Samoan'
74 : 'Other Native Hawaiian and Other Pacific Islander'
75 : 'Some Other Race'
76 : 'Two or More Races'
77 : 'White and Black or African American'
78 : 'White and American Indian and Alaska Native'
79 : 'White and Asian'
80 : 'White and Some Other Race'
81 : 'Black or African American and American Indian and Alaska Native'
82 : 'Black or African American and Some Other Race'
83 : 'Race alone or in combination with one or more other races'
84 : 'Total population'
85 : 'White'
86 : 'Black or African American'
87 : 'American Indian and Alaska Native'
88 : 'Asian'
89 : 'Native Hawaiian and Other Pacific Islander'
90 : 'Some Other Race'
91 : 'HISPANIC OR LATINO AND RACE'
92 : 'Total population'
93 : 'Hispanic or Latino (of any race)'
94 : 'Mexican'
95 : 'Puerto Rican'
96 : 'Cuban'
97 : 'Other Hispanic or Latino'
98 : 'Not Hispanic or Latino'
99 : 'White alone'
100 : 'Black or African American alone'
101 : 'American Indian and Alaska Native alone'
102 : 'Asian alone'
103 : 'Native Hawaiian and Other Pacific Islander alone'
104 : 'Some Other Race alone'
105 : 'Two or More Races'
106 : 'Two races including Some Other Race'
107 : 'Two races excluding Some Other Race, and three or more races'
108 : 'Total housing units'
109 : 'CITIZEN, VOTING AGE POPULATION'
110 : 'Citizen, 18 and over population'
111 : 'Male'
112 : 'Female'

In [4]:
duplicate_rows = df_dp05[df_dp05.duplicated(keep=False)]

display(duplicate_rows[["Label (Grouping)"]])

             Label (Grouping)
1            Total population
34           Total population
35                   One race
36          Two or More Races
37                   One race
76          Two or More Races
84           Total population
92           Total population

In [5]:
selected_rows = {
    "Total population": 1,
    "Median age (years)": 18,
    "65 years and over": 24,
    "85 years and over": 17
}

for label, row_index in selected_rows.items():
    print(f"\n{label} — row {row_index}")
    display(df_dp05.iloc[[row_index], :9])

Total population — row 1

,Label (Grouping),"Barnstable County, Massachusetts!!Estimate","Barnstable County, Massachusetts!!Margin of Error","Barnstable County, Massachusetts!!Percent","Barnstable County, Massachusetts!!Percent Margin of Error","Berkshire County, Massachusetts!!Estimate","Berkshire County, Massachusetts!!Margin of Error","Berkshire County, Massachusetts!!Percent","Berkshire County, Massachusetts!!Percent Margin of Error"
1,Total population,"231,668",*****,"231,668",(X),"129,430",*****,"129,430",(X)

Median age (years) — row 18

,Label (Grouping),"Barnstable County, Massachusetts!!Estimate","Barnstable County, Massachusetts!!Margin of Error","Barnstable County, Massachusetts!!Percent","Barnstable County, Massachusetts!!Percent Margin of Error","Berkshire County, Massachusetts!!Estimate","Berkshire County, Massachusetts!!Margin of Error","Berkshire County, Massachusetts!!Percent","Berkshire County, Massachusetts!!Percent Margin of Error"
18,Median age (years),55.4,±0.1,(X),(X),47.3,±0.3,(X),(X)

65 years and over — row 24

,Label (Grouping),"Barnstable County, Massachusetts!!Estimate","Barnstable County, Massachusetts!!Margin of Error","Barnstable County, Massachusetts!!Percent","Barnstable County, Massachusetts!!Percent Margin of Error","Berkshire County, Massachusetts!!Estimate","Berkshire County, Massachusetts!!Margin of Error","Berkshire County, Massachusetts!!Percent","Berkshire County, Massachusetts!!Percent Margin of Error"
24,65 years and over,"76,755",±191,33.1%,±0.1,"32,417",±42,25.0%,±0.1

85 years and over — row 17

,Label (Grouping),"Barnstable County, Massachusetts!!Estimate","Barnstable County, Massachusetts!!Margin of Error","Barnstable County, Massachusetts!!Percent","Barnstable County, Massachusetts!!Percent Margin of Error","Berkshire County, Massachusetts!!Estimate","Berkshire County, Massachusetts!!Margin of Error","Berkshire County, Massachusetts!!Percent","Berkshire County, Massachusetts!!Percent Margin of Error"
17,85 years and over,"9,462",±728,4.1%,±0.3,"4,095",±351,3.2%,±0.3